#!/usr/bin/env python

import glob
import os
import popen2

suffixes = [
    '.array',
    '.canvas',
    '.version'
    ]

directories = [
    os.path.join('qwt-sources', 'include'),
    os.path.join('qwt-sources', 'src')
    ]

patches = []

for suffix in suffixes:
    patch = ''
    for directory in directories:
        backups = glob.glob(os.path.join(directory, '*' + suffix))
        for backup in backups:
            file = backup[:-len(suffix)]
            if os.path.exists(file):
                stdin, stdout = os.popen2('diff -au %s %s' % (backup, file))
                patch += stdout.read() 
    patches.append((suffix, patch))
    output = open('qwt%s.patch' % suffix, 'w')
    print >> output, patch,
                
output = open('patches.py', 'w')
print >> output, 'patches =', patches    

# Local Variables: ***
# mode: python ***
# End: ***

